name: Production release to itch.io

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "itch.io"
  cancel-in-progress: true

jobs:
  generate-gamedata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate gamedata
        run: |
          php conversor-csv/convert.php

          cat ./projeto/Scripts/Data/GameData.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gamedata
          path: ./projeto/Scripts/Data/GameData.json

  build:
    runs-on: ubuntu-latest
    needs: generate-gamedata
    container:
      image: nawarian/godot:4.3-stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download generated gamedata
        uses: actions/download-artifact@v4
        with:
          name: gamedata
          path: ./projeto/Scripts/Data/

      - name: Build web
        env:
          HOME: /root
        run: |
          apt update && apt install -y zip

          mkdir build/
          godot --display-driver headless --verbose --export-release "Web" $(pwd)/build/index.html

          mv vendor/coi.min.js build/coi.min.js
          # sed -i '3 i <script src="coi.min.js"></script>' build/index.html
          zip -r build.zip build/
          rm -rf build
          mkdir build/
          mv build.zip build/artifact.zip
        working-directory: ./projeto

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: projeto/build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: nawarian/butler:latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Publish
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          /app/butler push build/artifact.zip ntmtst/caso-de-policia:html5
